---

- name: Add launchpad repo
  apt_repository: repo='ppa:webupd8team/java'
  notify:
    - update apt repository
- name: Make sure Oracle Java 7 JDK is installed
  apt: pkg={{ item }}
  with_items:
       - oracle-java7-installer
  tags:
    - java